// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-zta5lr97RvAXF0p5zIvslzRLLrpOD90',
    appId: '1:735552269809:web:d82a471d9c6c4d816ca850',
    messagingSenderId: '735552269809',
    projectId: 'gestionsocios-pintor',
    authDomain: 'gestionsocios-pintor.firebaseapp.com',
    storageBucket: 'gestionsocios-pintor.firebasestorage.app',
    measurementId: 'G-QVJVRGT95F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgOn7LmXL4W8tpVuauwewyW4DVebeozM',
    appId: '1:735552269809:android:66e392d03994947f6ca850',
    messagingSenderId: '735552269809',
    projectId: 'gestionsocios-pintor',
    storageBucket: 'gestionsocios-pintor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6d-xih_4N45zrhXLAFkK1KIQjlpKbjtM',
    appId: '1:735552269809:ios:64634254f7fd0a5d6ca850',
    messagingSenderId: '735552269809',
    projectId: 'gestionsocios-pintor',
    storageBucket: 'gestionsocios-pintor.firebasestorage.app',
    iosBundleId: 'com.example.gestionsocios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6d-xih_4N45zrhXLAFkK1KIQjlpKbjtM',
    appId: '1:735552269809:ios:64634254f7fd0a5d6ca850',
    messagingSenderId: '735552269809',
    projectId: 'gestionsocios-pintor',
    storageBucket: 'gestionsocios-pintor.firebasestorage.app',
    iosBundleId: 'com.example.gestionsocios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-zta5lr97RvAXF0p5zIvslzRLLrpOD90',
    appId: '1:735552269809:web:dec00093121361726ca850',
    messagingSenderId: '735552269809',
    projectId: 'gestionsocios-pintor',
    authDomain: 'gestionsocios-pintor.firebaseapp.com',
    storageBucket: 'gestionsocios-pintor.firebasestorage.app',
    measurementId: 'G-F15JW0PWCJ',
  );
}
